---
- name: "Install web services"
  hosts: web
  become: yes
  
  tasks:
    - name: "Installing package"
      yum: 
        name: "{{ web_pkg_name }}"
        state: latest
      notify: restart_httpd
    - name: "Open firewall port"
      firewalld: 
        service: "{{ web_fw_srv_name }}"
        state: enabled
        immediate: yes
        permanent: yes
  handlers: 
    - name: restart_httpd
      service: 
        name: "{{ web_srv_name }}"
        state: started
 

