---
- name: "Install web services"
  hosts: web
  become: yes
  
  tasks:
    - name: "Installing package"
      yum: 
        name: "{{ web_pkg_name }}"
        state: latest
      notify: restart_httpd  
  handlers: 
    - name: restart_httpd
      service: 
        name: "{{ web_srv_name }}"
        state: started
 

